services:
  database:
    container_name: todo
    image: mysql:8.4.0
    ports:
      - '13306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_DATABASE=todoDB'
      - 'MYSQL_USER=local'
      - 'MYSQL_PASSWORD=1234'
