services:
  database:
    container_name: todo
    image: mysql:8.4.0
    ports:
      - '13306:3306'
    volumes:
      - ./mysql_docker/data:/var/lib/mysql:rw
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_DATABASE=todo'
      - 'MYSQL_USER=local'
      - 'MYSQL_PASSWORD=1234'
