spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:13306/todo
    username: local
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
#  profiles:
#    include: oauth

jwt:
  # noinspection SpringBootApplicationYaml
  secret: ${JWT_SECRET}
  expiration_time: 3600000 # 1시간 = 1000 * 60 * 60 * 1

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080