spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:13306/todo
    username: local
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#  profiles:
#    include: oauth

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

jwt:
  secret: dGhlcm1lZGlhbm9yZXBheW5jZGVzdGxldGVjY2VsbGVyYXBwZXJjZGVzdG9nZWx5
